language: d
sudo: false
dist: trusty

addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev

d:
  - ldc-1.1.0
  - ldc-1.2.0
  - ldc-1.3.0
  - ldc-beta
  - dmd-2.073.2
  - dmd-2.074.1
  - dmd-2.075.1
  - dmd-beta

matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc-beta

script:
  - dub build
