language: d
sudo: false
dist: trusty

addons:
  apt:
    packages:
    - libevent-dev
    - libssl-dev

d:
  - ldc-1.2.0
  - ldc-1.3.0
  - ldc-beta
  - dmd-2.074.1
  - dmd-2.075.1
  - dmd-beta

matrix:
  allow_failures:
    - d: dmd-beta
    - d: ldc-beta

before_install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub build
  - dub fetch dscanner
  - dub run dscanner -- --styleCheck log core 2>&1 || echo "Style check!"
  - dub run dscanner -- --syntaxCheck log core 2>&1 || echo "Syntax check!"
  - dub run dscanner -- --sloc log core
  - dub run big-d:test --combined
  - rm test*.lst 2>&1 || echo "Remove test .lst"
  - dub build --build=ddox
  - dub build big-d:log --build=ddox
  - ./doveralls
  - cd examples/log/udplogger/basic && dub build && cd ../../../../
  - cd examples/log/udplogger/logstash && dub build && cd ../../../../
  - cd examples/log/tcplogger/basic && dub build && cd ../../../../
  - cd examples/log/tcplogger/logstash && dub build && cd ../../../../

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
