// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'big.log.logservice', kind: "module", path: './big/log/logservice.html', attributes: []},
{name: 'big.log.logservice.LogService', kind: "classdeclaration", path: './big/log/logservice/LogService.html', attributes: []},
{name: 'big.log.logservice.LogService.getLogger', kind: "functiondeclaration", path: './big/log/logservice/LogService.getLogger.html', attributes: ["safe"]},
{name: 'big.log.logservice.LogService.this', kind: "functiondeclaration", path: './big/log/logservice/LogService.this.html', attributes: ["safe"]},
{name: 'big.log.tcplogger', kind: "module", path: './big/log/tcplogger.html', attributes: []},
{name: 'big.log.tcplogger.TCPLogger', kind: "classdeclaration", path: './big/log/tcplogger/TCPLogger.html', attributes: []},
{name: 'big.log.tcplogger.TCPLogger.this', kind: "functiondeclaration", path: './big/log/tcplogger/TCPLogger.this.html', attributes: ["safe"]},
{name: 'big.log.tcplogger.TCPLogger.writeLogMsg', kind: "functiondeclaration", path: './big/log/tcplogger/TCPLogger.writeLogMsg.html', attributes: ["override", "trusted"]},
{name: 'big.log.udplogger', kind: "module", path: './big/log/udplogger.html', attributes: []},
{name: 'big.log.udplogger.UDPLogger', kind: "classdeclaration", path: './big/log/udplogger/UDPLogger.html', attributes: []},
{name: 'big.log.udplogger.UDPLogger.this', kind: "functiondeclaration", path: './big/log/udplogger/UDPLogger.this.html', attributes: ["safe"]},
{name: 'big.log.udplogger.UDPLogger.writeLogMsg', kind: "functiondeclaration", path: './big/log/udplogger/UDPLogger.writeLogMsg.html', attributes: ["override", "trusted"]},
{name: 'big.log', kind: "module", path: './big/log.html', attributes: []},
];
